repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: ^(.cicd|.infra)/
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
